name: Compilar Mod Voidborn

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Descompactar Mod
        run: |
          mkdir -p extrair_temp
          unzip -o *.zip -d extrair_temp/
          BUILD_FILE=$(find extrair_temp -name "build.gradle" | head -n 1)
          if [ -n "$BUILD_FILE" ]; then
            PROJECT_DIR=$(dirname "$BUILD_FILE")
            cp -r "$PROJECT_DIR"/* .
          fi
          rm -rf extrair_temp

      - name: Gerar Executavel e Compilar
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew
          ./gradlew build --stacktrace -x test --no-daemon

      - name: Enviar arquivo .jar pronto
        uses: actions/upload-artifact@v4
        with:
          name: Voidborn-Mod-JAR
          path: "**/build/libs/*.jar"
